// <auto-generated />
using ERMTest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ERMTest.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("ERMTest.Data.DataPK", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("FreeDisks")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FreeOfMemory")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalDisks")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalMemory")
                        .HasColumnType("numeric");

                    b.Property<decimal>("UsageCPU")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("DataPK");
                });
#pragma warning restore 612, 618
        }
    }
}
